repos:
-   repo: local
    hooks:
    -   id: black
        name: black
        entry: venv/bin/black
        language: python
        types: [python]
-   repo: local
    hooks:
    -   id: pytest
        name: pytest
        entry: veenv/bin/pytest
        language: python
        types: [python]
        pass_filenames: false
